// packages/angular/src/lib/link/link.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "cp-link",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <a
      [href]="href"
      [class]="wrapperClasses"
      [attr.aria-disabled]="disabled ? 'true' : null"
      [attr.target]="external ? '_blank' : null"
      [attr.rel]="external ? 'noopener noreferrer' : null"
    >
      <ng-content></ng-content>
      <span *ngIf="external" class="cp-link__external-icon" aria-hidden="true"></span>
    </a>
  `,
})
export class CpLinkComponent {
  @Input() href = "";
  @Input() muted = false;
  @Input() disabled = false;
  @Input() external = false;

  get wrapperClasses(): string {
    return ["cp-link", this.muted ? "cp-link--muted" : ""].filter(Boolean).join(" ");
  }
}

// packages/react/src/components/Link/Link.tsx
import { forwardRef } from "react";
import type { AnchorHTMLAttributes } from "react";

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  /** Estilo visual menos proeminente, para links secundários dentro de texto de apoio. */
  muted?: boolean;
  disabled?: boolean;
  /** Marca o link como externo: adiciona indicador visual e target="_blank" com rel seguro. */
  external?: boolean;
}

export const Link = forwardRef<HTMLAnchorElement, LinkProps>(function Link(
  { muted = false, disabled = false, external = false, className, children, target, rel, ...rest },
  ref
) {
  return (
    <a
      ref={ref}
      className={["cp-link", muted && "cp-link--muted", className].filter(Boolean).join(" ")}
      aria-disabled={disabled || undefined}
      target={external ? "_blank" : target}
      rel={external ? "noopener noreferrer" : rel}
      {...rest}
    >
      {children}
      {external && <span className="cp-link__external-icon" aria-hidden="true" />}
    </a>
  );
});
