// packages/angular/src/lib/accordion/accordion.component.ts
import {
  AfterContentChecked,
  ChangeDetectionStrategy,
  Component,
  ContentChildren,
  ElementRef,
  Input,
  QueryList,
  ViewChildren,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { CpAccordionPanelComponent } from "./accordion-panel.component";

export interface CpAccordionItem {
  id: string;
  title: string;
  disabled?: boolean;
}

let uniqueId = 0;

@Component({
  selector: "cp-accordion",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="cp-accordion">
      <div *ngFor="let item of items; let i = index" class="cp-accordion__item">
        <h3 class="cp-accordion__header">
          <button
            #headerButton
            type="button"
            [id]="headerIdFor(item.id)"
            [class]="triggerClasses(item)"
            [attr.aria-expanded]="isOpen(item.id)"
            [attr.aria-controls]="panelIdFor(item.id)"
            [disabled]="item.disabled"
            (click)="toggle(item.id)"
            (keydown)="onKeydown($event, i)"
          >
            <span class="cp-accordion__icon" aria-hidden="true"></span>
            {{ item.title }}
          </button>
        </h3>
      </div>
      <ng-content></ng-content>
    </div>
  `,
})
export class CpAccordionComponent implements AfterContentChecked {
  @Input() items: CpAccordionItem[] = [];
  @Input() allowMultiple = false;
  @Input() defaultOpenIds: string[] = [];

  @ViewChildren("headerButton") headerButtons!: QueryList<ElementRef<HTMLButtonElement>>;
  @ContentChildren(CpAccordionPanelComponent, { descendants: true })
  panels?: QueryList<CpAccordionPanelComponent>;

  private openIds: string[] = [];
  private initialized = false;
  readonly instanceId = `cp-accordion-${uniqueId++}`;

  ngAfterContentChecked(): void {
    if (!this.initialized) {
      this.openIds = [...this.defaultOpenIds];
      this.initialized = true;
    }
    this.panels?.forEach((panel) => {
      panel.updateState(
        this.isOpen(panel.id),
        this.headerIdFor(panel.id),
        this.panelIdFor(panel.id)
      );
    });
  }

  headerIdFor(id: string): string {
    return `${this.instanceId}-header-${id}`;
  }

  panelIdFor(id: string): string {
    return `${this.instanceId}-panel-${id}`;
  }

  isOpen(id: string): boolean {
    return this.openIds.includes(id);
  }

  triggerClasses(item: CpAccordionItem): string {
    return ["cp-accordion__trigger", this.isOpen(item.id) ? "cp-accordion__trigger--open" : ""]
      .filter(Boolean)
      .join(" ");
  }

  toggle(id: string): void {
    const open = this.isOpen(id);
    if (this.allowMultiple) {
      this.openIds = open ? this.openIds.filter((openId) => openId !== id) : [...this.openIds, id];
    } else {
      this.openIds = open ? [] : [id];
    }
  }

  onKeydown(event: KeyboardEvent, index: number): void {
    let nextIndex: number | null = null;
    if (event.key === "ArrowDown") nextIndex = (index + 1) % this.items.length;
    else if (event.key === "ArrowUp") nextIndex = (index - 1 + this.items.length) % this.items.length;
    else if (event.key === "Home") nextIndex = 0;
    else if (event.key === "End") nextIndex = this.items.length - 1;

    if (nextIndex !== null) {
      event.preventDefault();
      this.headerButtons.get(nextIndex)?.nativeElement.focus();
    }
  }
}

// packages/react/src/components/Accordion/Accordion.tsx
import { useId, useRef, useState } from "react";
import type { KeyboardEvent, ReactNode } from "react";

export interface AccordionItem {
  id: string;
  title: ReactNode;
  content: ReactNode;
  disabled?: boolean;
}

export interface AccordionProps {
  items: AccordionItem[];
  /** Permite vários painéis abertos simultaneamente. Predefinição: false (apenas um por vez). */
  allowMultiple?: boolean;
  defaultOpenIds?: string[];
}

export function Accordion({ items, allowMultiple = false, defaultOpenIds = [] }: AccordionProps) {
  const [openIds, setOpenIds] = useState<string[]>(defaultOpenIds);
  const idBase = useId();
  const headerRefs = useRef<Record<string, HTMLButtonElement | null>>({});

  function toggle(id: string) {
    setOpenIds((current) => {
      const isOpen = current.includes(id);
      if (allowMultiple) {
        return isOpen ? current.filter((openId) => openId !== id) : [...current, id];
      }
      return isOpen ? [] : [id];
    });
  }

  function onKeyDown(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    let nextIndex: number | null = null;
    if (event.key === "ArrowDown") nextIndex = (index + 1) % items.length;
    else if (event.key === "ArrowUp") nextIndex = (index - 1 + items.length) % items.length;
    else if (event.key === "Home") nextIndex = 0;
    else if (event.key === "End") nextIndex = items.length - 1;

    if (nextIndex !== null) {
      event.preventDefault();
      headerRefs.current[items[nextIndex].id]?.focus();
    }
  }

  return (
    <div className="cp-accordion">
      {items.map((item, index) => {
        const isOpen = openIds.includes(item.id);
        return (
          <div key={item.id} className="cp-accordion__item">
            <h3 className="cp-accordion__header">
              <button
                ref={(el) => {
                  headerRefs.current[item.id] = el;
                }}
                type="button"
                className={["cp-accordion__trigger", isOpen && "cp-accordion__trigger--open"]
                  .filter(Boolean)
                  .join(" ")}
                aria-expanded={isOpen}
                aria-controls={`${idBase}-panel-${item.id}`}
                id={`${idBase}-header-${item.id}`}
                disabled={item.disabled}
                onClick={() => toggle(item.id)}
                onKeyDown={(event) => onKeyDown(event, index)}
              >
                <span className="cp-accordion__icon" aria-hidden="true" />
                {item.title}
              </button>
            </h3>
            {isOpen && (
              <div
                role="region"
                id={`${idBase}-panel-${item.id}`}
                aria-labelledby={`${idBase}-header-${item.id}`}
                className="cp-accordion__panel"
              >
                {item.content}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
