// packages/react/src/components/Notification/InlineNotification.tsx
import type { ReactNode } from "react";

export type NotificationStatus = "info" | "success" | "warning" | "danger";

export interface InlineNotificationProps {
  status?: NotificationStatus;
  title: ReactNode;
  description?: ReactNode;
  onClose?: () => void;
  className?: string;
}

export function InlineNotification({
  status = "info",
  title,
  description,
  onClose,
  className,
}: InlineNotificationProps) {
  return (
    <div
      className={["cp-notification", `cp-notification--${status}`, className]
        .filter(Boolean)
        .join(" ")}
      role={status === "danger" ? "alert" : "status"}
    >
      <span className="cp-notification__icon" aria-hidden="true" />
      <div className="cp-notification__content">
        <p className="cp-notification__title">{title}</p>
        {description && <p className="cp-notification__description">{description}</p>}
      </div>
      {onClose && (
        <button
          type="button"
          className="cp-notification__close"
          aria-label="Fechar notificação"
          onClick={onClose}
        >
          ×
        </button>
      )}
    </div>
  );
}

// packages/angular/src/lib/notification/inline-notification.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";

export type CpNotificationStatus = "info" | "success" | "warning" | "danger";

@Component({
  selector: "cp-inline-notification",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="wrapperClasses" [attr.role]="status === 'danger' ? 'alert' : 'status'">
      <span class="cp-notification__icon" aria-hidden="true"></span>
      <div class="cp-notification__content">
        <p class="cp-notification__title">{{ title }}</p>
        <p *ngIf="description" class="cp-notification__description">{{ description }}</p>
      </div>
      <button
        *ngIf="dismissible"
        type="button"
        class="cp-notification__close"
        aria-label="Fechar notificação"
        (click)="close.emit()"
      >
        ×
      </button>
    </div>
  `,
})
export class CpInlineNotificationComponent {
  @Input() status: CpNotificationStatus = "info";
  @Input() title = "";
  @Input() description = "";
  @Input() dismissible = false;
  @Output() close = new EventEmitter<void>();

  get wrapperClasses(): string {
    return ["cp-notification", `cp-notification--${this.status}`].join(" ");
  }
}
