// packages/angular/src/lib/number-input/number-input.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";
import type { CpFieldSize } from "../text-input/text-input.component";

let uniqueId = 0;

@Component({
  selector: "cp-number-input",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="cp-field">
      <label *ngIf="label" [for]="inputId" [class]="labelClasses">{{ label }}</label>
      <div [class]="wrapperClasses">
        <button
          type="button"
          class="cp-number-input__step"
          aria-label="Diminuir"
          [disabled]="disabled || !canDecrement"
          (click)="valueChange.emit(clamp(value - step))"
        >
          −
        </button>
        <input
          [id]="inputId"
          type="number"
          [required]="required"
          [disabled]="disabled"
          [attr.min]="min"
          [attr.max]="max"
          [step]="step"
          [value]="value"
          [attr.aria-invalid]="invalid ? 'true' : null"
          [attr.aria-describedby]="errorText || helperText ? helperId : null"
          [class]="inputClasses"
          (input)="onInput($event)"
        />
        <button
          type="button"
          class="cp-number-input__step"
          aria-label="Aumentar"
          [disabled]="disabled || !canIncrement"
          (click)="valueChange.emit(clamp(value + step))"
        >
          +
        </button>
      </div>
      <span *ngIf="errorText || helperText" [id]="helperId" [class]="helperClasses">
        {{ errorText || helperText }}
      </span>
    </div>
  `,
})
export class CpNumberInputComponent {
  @Input() label = "";
  @Input() helperText = "";
  @Input() errorText = "";
  @Input() size: CpFieldSize = "md";
  @Input() required = false;
  @Input() disabled = false;
  @Input() value = 0;
  @Input() min?: number;
  @Input() max?: number;
  @Input() step = 1;
  @Output() valueChange = new EventEmitter<number>();

  readonly inputId = `cp-number-input-${uniqueId++}`;
  readonly helperId = `${this.inputId}-helper`;

  get invalid(): boolean {
    return Boolean(this.errorText);
  }

  get canDecrement(): boolean {
    return this.min === undefined || this.value > this.min;
  }

  get canIncrement(): boolean {
    return this.max === undefined || this.value < this.max;
  }

  get labelClasses(): string {
    return ["cp-field__label", this.required ? "cp-field__label--required" : ""]
      .filter(Boolean)
      .join(" ");
  }

  get wrapperClasses(): string {
    return ["cp-number-input", this.invalid ? "cp-number-input--invalid" : ""]
      .filter(Boolean)
      .join(" ");
  }

  get inputClasses(): string {
    return ["cp-input", "cp-number-input__field", `cp-input--${this.size}`].join(" ");
  }

  get helperClasses(): string {
    return ["cp-field__helper", this.errorText ? "cp-field__helper--error" : ""]
      .filter(Boolean)
      .join(" ");
  }

  clamp(next: number): number {
    let result = next;
    if (this.min !== undefined) result = Math.max(this.min, result);
    if (this.max !== undefined) result = Math.min(this.max, result);
    return result;
  }

  onInput(event: Event): void {
    this.valueChange.emit(this.clamp(Number((event.target as HTMLInputElement).value)));
  }
}

// packages/react/src/components/NumberInput/NumberInput.tsx
import { forwardRef, useId } from "react";
import type { InputHTMLAttributes, ReactNode } from "react";
import type { FieldSize } from "../TextInput";

export interface NumberInputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, "size" | "type" | "onChange"> {
  label?: ReactNode;
  helperText?: ReactNode;
  errorText?: ReactNode;
  size?: FieldSize;
  value?: number;
  step?: number;
  onChange?: (value: number) => void;
}

export const NumberInput = forwardRef<HTMLInputElement, NumberInputProps>(function NumberInput(
  {
    label,
    helperText,
    errorText,
    size = "md",
    required,
    id,
    className,
    value = 0,
    min,
    max,
    step = 1,
    onChange,
    disabled,
    ...rest
  },
  ref
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const helperId = `${inputId}-helper`;
  const invalid = Boolean(errorText);

  function clamp(next: number): number {
    let result = next;
    if (min !== undefined) result = Math.max(Number(min), result);
    if (max !== undefined) result = Math.min(Number(max), result);
    return result;
  }

  const canDecrement = min === undefined || value > Number(min);
  const canIncrement = max === undefined || value < Number(max);

  return (
    <div className="cp-field">
      {label && (
        <label
          htmlFor={inputId}
          className={["cp-field__label", required && "cp-field__label--required"]
            .filter(Boolean)
            .join(" ")}
        >
          {label}
        </label>
      )}
      <div
        className={["cp-number-input", invalid && "cp-number-input--invalid"]
          .filter(Boolean)
          .join(" ")}
      >
        <button
          type="button"
          className="cp-number-input__step"
          aria-label="Diminuir"
          disabled={disabled || !canDecrement}
          onClick={() => onChange?.(clamp(value - step))}
        >
          −
        </button>
        <input
          ref={ref}
          id={inputId}
          type="number"
          required={required}
          disabled={disabled}
          min={min}
          max={max}
          step={step}
          value={value}
          aria-invalid={invalid || undefined}
          aria-describedby={errorText || helperText ? helperId : undefined}
          className={["cp-input", "cp-number-input__field", `cp-input--${size}`, className]
            .filter(Boolean)
            .join(" ")}
          onChange={(event) => onChange?.(clamp(Number(event.target.value)))}
          {...rest}
        />
        <button
          type="button"
          className="cp-number-input__step"
          aria-label="Aumentar"
          disabled={disabled || !canIncrement}
          onClick={() => onChange?.(clamp(value + step))}
        >
          +
        </button>
      </div>
      {(errorText || helperText) && (
        <span
          id={helperId}
          className={["cp-field__helper", errorText && "cp-field__helper--error"]
            .filter(Boolean)
            .join(" ")}
        >
          {errorText || helperText}
        </span>
      )}
    </div>
  );
});
