// packages/react/src/components/Tile/Tile.tsx
import type { AnchorHTMLAttributes, ButtonHTMLAttributes, ReactNode } from "react";

interface TileBaseProps {
  icon?: ReactNode;
  title: ReactNode;
  description?: ReactNode;
}

export type TileProps =
  | (TileBaseProps & AnchorHTMLAttributes<HTMLAnchorElement> & { href: string })
  | (TileBaseProps & ButtonHTMLAttributes<HTMLButtonElement> & { href?: undefined });

export function Tile({ icon, title, description, className, ...rest }: TileProps) {
  const classes = ["cp-tile", className].filter(Boolean).join(" ");
  const content = (
    <>
      {icon && (
        <span className="cp-tile__icon" aria-hidden="true">
          {icon}
        </span>
      )}
      <span className="cp-tile__title">{title}</span>
      {description && <span className="cp-tile__description">{description}</span>}
    </>
  );

  if ("href" in rest && rest.href) {
    return (
      <a className={classes} {...(rest as AnchorHTMLAttributes<HTMLAnchorElement>)}>
        {content}
      </a>
    );
  }

  return (
    <button
      type="button"
      className={classes}
      {...(rest as ButtonHTMLAttributes<HTMLButtonElement>)}
    >
      {content}
    </button>
  );
}

// packages/angular/src/lib/tile/tile.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "cp-tile",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <a *ngIf="href" [href]="href" class="cp-tile">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </a>
    <button *ngIf="!href" type="button" class="cp-tile">
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </button>
    <ng-template #content>
      <span class="cp-tile__icon" *ngIf="icon" aria-hidden="true">{{ icon }}</span>
      <span class="cp-tile__title">{{ title }}</span>
      <span class="cp-tile__description" *ngIf="description">{{ description }}</span>
    </ng-template>
  `,
})
export class CpTileComponent {
  @Input() title = "";
  @Input() description = "";
  @Input() href = "";
  @Input() icon = "";
}
