// packages/angular/src/lib/structured-list/structured-list.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "cp-structured-list",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <table class="cp-structured-list" [attr.aria-label]="ariaLabel">
      <thead>
        <tr>
          <th *ngFor="let header of headers" scope="col">{{ header }}</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let row of rows">
          <td *ngFor="let cell of row">{{ cell }}</td>
        </tr>
      </tbody>
    </table>
  `,
})
export class CpStructuredListComponent {
  @Input() headers: string[] = [];
  @Input() rows: (string | number)[][] = [];
  @Input() ariaLabel = "";
}

// packages/react/src/components/StructuredList/StructuredList.tsx
import type { ReactNode } from "react";

export interface StructuredListProps {
  headers: string[];
  rows: ReactNode[][];
  "aria-label"?: string;
}

export function StructuredList({ headers, rows, "aria-label": ariaLabel }: StructuredListProps) {
  return (
    <table className="cp-structured-list" aria-label={ariaLabel}>
      <thead>
        <tr>
          {headers.map((header) => (
            <th key={header} scope="col">
              {header}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, rowIndex) => (
          <tr key={rowIndex}>
            {row.map((cell, cellIndex) => (
              <td key={cellIndex}>{cell}</td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
