// packages/react/src/components/Shell/Header.tsx
import type { ReactNode } from "react";

export interface HeaderProps {
  brand: string;
  brandHref?: string;
  navOpen?: boolean;
  onMenuToggle?: () => void;
  children?: ReactNode;
}

export function Header({ brand, brandHref = "#", navOpen = false, onMenuToggle, children }: HeaderProps) {
  return (
    <header className="cp-header">
      {onMenuToggle && (
        <button
          type="button"
          className="cp-header__menu-button"
          aria-label={navOpen ? "Fechar menu de navegação" : "Abrir menu de navegação"}
          aria-expanded={navOpen}
          onClick={onMenuToggle}
        >
          <span aria-hidden="true">{navOpen ? "✕" : "☰"}</span>
        </button>
      )}
      <a className="cp-header__brand" href={brandHref}>
        {brand}
      </a>
      <div className="cp-header__actions">{children}</div>
    </header>
  );
}

// packages/angular/src/lib/shell/header.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "cp-header",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <header class="cp-header">
      <button
        *ngIf="menuButton"
        type="button"
        class="cp-header__menu-button"
        [attr.aria-label]="navOpen ? 'Fechar menu de navegação' : 'Abrir menu de navegação'"
        [attr.aria-expanded]="navOpen"
        (click)="menuToggle.emit()"
      >
        <span aria-hidden="true">{{ navOpen ? "✕" : "☰" }}</span>
      </button>
      <a class="cp-header__brand" [attr.href]="brandHref">{{ brand }}</a>
      <div class="cp-header__actions">
        <ng-content></ng-content>
      </div>
    </header>
  `,
})
export class CpHeaderComponent {
  @Input() brand = "";
  @Input() brandHref = "#";
  @Input() menuButton = false;
  @Input() navOpen = false;
  @Output() menuToggle = new EventEmitter<void>();
}
