// packages/angular/src/lib/skeleton/skeleton.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

export type CpSkeletonVariant = "text" | "circle" | "rect";

@Component({
  selector: "cp-skeleton",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span
      [class]="wrapperClasses"
      [style.width]="width"
      [style.height]="height"
      role="presentation"
      aria-hidden="true"
    ></span>
  `,
})
export class CpSkeletonComponent {
  @Input() variant: CpSkeletonVariant = "text";
  @Input() width?: string;
  @Input() height?: string;

  get wrapperClasses(): string {
    return ["cp-skeleton", `cp-skeleton--${this.variant}`].join(" ");
  }
}

// packages/react/src/components/Skeleton/Skeleton.tsx
import type { HTMLAttributes } from "react";

export type SkeletonVariant = "text" | "circle" | "rect";

export interface SkeletonProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: SkeletonVariant;
  width?: string | number;
  height?: string | number;
}

export function Skeleton({ variant = "text", width, height, className, style, ...rest }: SkeletonProps) {
  return (
    <span
      className={["cp-skeleton", `cp-skeleton--${variant}`, className].filter(Boolean).join(" ")}
      style={{ width, height, ...style }}
      role="presentation"
      aria-hidden="true"
      {...rest}
    />
  );
}
