// packages/angular/src/lib/toggle/toggle.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";

let uniqueId = 0;

@Component({
  selector: "cp-toggle",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [for]="inputId" [class]="wrapperClasses">
      <input
        type="checkbox"
        role="switch"
        [id]="inputId"
        class="cp-toggle__input"
        [disabled]="disabled"
        [checked]="checked"
        (change)="onChange($event)"
      />
      <span class="cp-toggle__track" aria-hidden="true">
        <span class="cp-toggle__thumb"></span>
      </span>
      <span>{{ label }}</span>
    </label>
  `,
})
export class CpToggleComponent {
  @Input() label = "";
  @Input() disabled = false;
  @Input() checked = false;
  @Output() checkedChange = new EventEmitter<boolean>();

  readonly inputId = `cp-toggle-${uniqueId++}`;

  get wrapperClasses(): string {
    return ["cp-toggle", this.disabled ? "cp-toggle--disabled" : ""].filter(Boolean).join(" ");
  }

  onChange(event: Event): void {
    this.checked = (event.target as HTMLInputElement).checked;
    this.checkedChange.emit(this.checked);
  }
}

// packages/react/src/components/Toggle/Toggle.tsx
import { forwardRef, useId } from "react";
import type { InputHTMLAttributes, ReactNode } from "react";

export interface ToggleProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "type"> {
  label: ReactNode;
}

export const Toggle = forwardRef<HTMLInputElement, ToggleProps>(function Toggle(
  { label, disabled, className, id, ...rest },
  ref
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;

  return (
    <label
      htmlFor={inputId}
      className={["cp-toggle", disabled && "cp-toggle--disabled", className]
        .filter(Boolean)
        .join(" ")}
    >
      <input
        ref={ref}
        type="checkbox"
        role="switch"
        id={inputId}
        disabled={disabled}
        className="cp-toggle__input"
        {...rest}
      />
      <span className="cp-toggle__track" aria-hidden="true">
        <span className="cp-toggle__thumb" />
      </span>
      <span>{label}</span>
    </label>
  );
});
