// packages/react/src/components/Select/Select.tsx
import { forwardRef, useId } from "react";
import type { ReactNode, SelectHTMLAttributes } from "react";
import type { FieldSize } from "../TextInput";

export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface SelectProps extends Omit<SelectHTMLAttributes<HTMLSelectElement>, "size"> {
  label?: ReactNode;
  helperText?: ReactNode;
  errorText?: ReactNode;
  size?: FieldSize;
  options: SelectOption[];
  placeholder?: string;
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(function Select(
  {
    label,
    helperText,
    errorText,
    size = "md",
    required,
    id,
    className,
    options,
    placeholder,
    ...rest
  },
  ref
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const helperId = `${inputId}-helper`;
  const invalid = Boolean(errorText);

  return (
    <div className="cp-field">
      {label && (
        <label
          htmlFor={inputId}
          className={["cp-field__label", required && "cp-field__label--required"]
            .filter(Boolean)
            .join(" ")}
        >
          {label}
        </label>
      )}
      <select
        ref={ref}
        id={inputId}
        required={required}
        aria-invalid={invalid || undefined}
        aria-describedby={errorText || helperText ? helperId : undefined}
        className={["cp-input", `cp-input--${size}`, invalid && "cp-input--invalid", className]
          .filter(Boolean)
          .join(" ")}
        {...rest}
      >
        {placeholder && (
          <option value="" disabled hidden>
            {placeholder}
          </option>
        )}
        {options.map((option) => (
          <option key={option.value} value={option.value} disabled={option.disabled}>
            {option.label}
          </option>
        ))}
      </select>
      {(errorText || helperText) && (
        <span
          id={helperId}
          className={["cp-field__helper", errorText && "cp-field__helper--error"]
            .filter(Boolean)
            .join(" ")}
        >
          {errorText || helperText}
        </span>
      )}
    </div>
  );
});

// packages/angular/src/lib/select/select.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";
import type { CpFieldSize } from "../text-input/text-input.component";

export interface CpSelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

let uniqueId = 0;

@Component({
  selector: "cp-select",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="cp-field">
      <label *ngIf="label" [for]="inputId" [class]="labelClasses">{{ label }}</label>
      <select
        [id]="inputId"
        [required]="required"
        [disabled]="disabled"
        [value]="value"
        [attr.aria-invalid]="invalid ? 'true' : null"
        [attr.aria-describedby]="errorText || helperText ? helperId : null"
        [class]="inputClasses"
        (change)="onChange($event)"
      >
        <option *ngIf="placeholder" value="" disabled hidden>{{ placeholder }}</option>
        <option *ngFor="let option of options" [value]="option.value" [disabled]="option.disabled">
          {{ option.label }}
        </option>
      </select>
      <span *ngIf="errorText || helperText" [id]="helperId" [class]="helperClasses">
        {{ errorText || helperText }}
      </span>
    </div>
  `,
})
export class CpSelectComponent {
  @Input() label = "";
  @Input() helperText = "";
  @Input() errorText = "";
  @Input() size: CpFieldSize = "md";
  @Input() required = false;
  @Input() disabled = false;
  @Input() options: CpSelectOption[] = [];
  @Input() placeholder = "";
  @Input() value = "";
  @Output() valueChange = new EventEmitter<string>();

  readonly inputId = `cp-select-${uniqueId++}`;
  readonly helperId = `${this.inputId}-helper`;

  get invalid(): boolean {
    return Boolean(this.errorText);
  }

  get labelClasses(): string {
    return ["cp-field__label", this.required ? "cp-field__label--required" : ""]
      .filter(Boolean)
      .join(" ");
  }

  get inputClasses(): string {
    return ["cp-input", `cp-input--${this.size}`, this.invalid ? "cp-input--invalid" : ""]
      .filter(Boolean)
      .join(" ");
  }

  get helperClasses(): string {
    return ["cp-field__helper", this.errorText ? "cp-field__helper--error" : ""]
      .filter(Boolean)
      .join(" ");
  }

  onChange(event: Event): void {
    this.value = (event.target as HTMLSelectElement).value;
    this.valueChange.emit(this.value);
  }
}
