// packages/react/src/components/Pagination/Pagination.tsx
export interface PaginationProps {
  page: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  "aria-label"?: string;
}

export function Pagination({
  page,
  totalPages,
  onPageChange,
  "aria-label": ariaLabel = "Paginação",
}: PaginationProps) {
  const canGoPrevious = page > 1;
  const canGoNext = page < totalPages;

  return (
    <nav className="cp-pagination" aria-label={ariaLabel}>
      <span className="cp-pagination__status">
        Página {page} de {totalPages}
      </span>
      <div className="cp-pagination__nav">
        <button
          type="button"
          className="cp-pagination__button"
          disabled={!canGoPrevious}
          aria-label="Página anterior"
          onClick={() => onPageChange(page - 1)}
        >
          ‹
        </button>
        <button
          type="button"
          className="cp-pagination__button"
          disabled={!canGoNext}
          aria-label="Página seguinte"
          onClick={() => onPageChange(page + 1)}
        >
          ›
        </button>
      </div>
    </nav>
  );
}

// packages/angular/src/lib/pagination/pagination.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "cp-pagination",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="cp-pagination" [attr.aria-label]="ariaLabel">
      <span class="cp-pagination__status">Página {{ page }} de {{ totalPages }}</span>
      <div class="cp-pagination__nav">
        <button
          type="button"
          class="cp-pagination__button"
          [disabled]="page <= 1"
          aria-label="Página anterior"
          (click)="pageChange.emit(page - 1)"
        >
          ‹
        </button>
        <button
          type="button"
          class="cp-pagination__button"
          [disabled]="page >= totalPages"
          aria-label="Página seguinte"
          (click)="pageChange.emit(page + 1)"
        >
          ›
        </button>
      </div>
    </nav>
  `,
})
export class CpPaginationComponent {
  @Input() page = 1;
  @Input() totalPages = 1;
  @Input() ariaLabel = "Paginação";
  @Output() pageChange = new EventEmitter<number>();
}
