// packages/react/src/components/Button/Button.tsx
import { forwardRef } from "react";
import type { ButtonHTMLAttributes, ReactNode } from "react";

export type ButtonVariant = "primary" | "accent" | "secondary" | "ghost" | "danger";
export type ButtonSize = "sm" | "md" | "lg";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Estilo visual do botão. `primary` para a ação principal do contexto, `accent` para chamadas de destaque. */
  variant?: ButtonVariant;
  size?: ButtonSize;
  /** Mostra um spinner e desativa o botão, mantendo o texto para leitores de ecrã via aria-busy. */
  loading?: boolean;
  fullWidth?: boolean;
  leadingIcon?: ReactNode;
  trailingIcon?: ReactNode;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  {
    variant = "primary",
    size = "md",
    loading = false,
    fullWidth = false,
    leadingIcon,
    trailingIcon,
    disabled,
    className,
    children,
    type = "button",
    ...rest
  },
  ref
) {
  const classes = [
    "cp-button",
    `cp-button--${variant}`,
    `cp-button--${size}`,
    loading && "cp-button--loading",
    fullWidth && "cp-button--full-width",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <button
      ref={ref}
      type={type}
      className={classes}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      {...rest}
    >
      {loading && <span className="cp-button__spinner" aria-hidden="true" />}
      {!loading && leadingIcon}
      <span>{children}</span>
      {!loading && trailingIcon}
    </button>
  );
});

// packages/angular/src/lib/button/button.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

export type CpButtonVariant = "primary" | "accent" | "secondary" | "ghost" | "danger";
export type CpButtonSize = "sm" | "md" | "lg";

@Component({
  selector: "cp-button",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      [type]="type"
      [class]="classes"
      [disabled]="disabled || loading"
      [attr.aria-busy]="loading ? 'true' : null"
    >
      <span *ngIf="loading" class="cp-button__spinner" aria-hidden="true"></span>
      <ng-content *ngIf="!loading" select="[cpLeadingIcon]"></ng-content>
      <span><ng-content></ng-content></span>
      <ng-content *ngIf="!loading" select="[cpTrailingIcon]"></ng-content>
    </button>
  `,
})
export class CpButtonComponent {
  @Input() variant: CpButtonVariant = "primary";
  @Input() size: CpButtonSize = "md";
  /** Mostra um spinner e desativa o botão, mantendo aria-busy para leitores de ecrã. */
  @Input() loading = false;
  @Input() fullWidth = false;
  @Input() disabled = false;
  @Input() type: "button" | "submit" | "reset" = "button";

  get classes(): string {
    return [
      "cp-button",
      `cp-button--${this.variant}`,
      `cp-button--${this.size}`,
      this.loading ? "cp-button--loading" : "",
      this.fullWidth ? "cp-button--full-width" : "",
    ]
      .filter(Boolean)
      .join(" ");
  }
}
