// packages/react/src/components/Search/Search.tsx
import { forwardRef, useId } from "react";
import type { InputHTMLAttributes } from "react";
import type { FieldSize } from "../TextInput";

export interface SearchProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "size" | "type"> {
  label?: string;
  size?: FieldSize;
  onClear?: () => void;
}

export const Search = forwardRef<HTMLInputElement, SearchProps>(function Search(
  { label = "Pesquisar", size = "md", id, className, value, onClear, ...rest },
  ref
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const showClear = Boolean(onClear && value);

  return (
    <div className="cp-search">
      <span className="cp-search__icon" aria-hidden="true" />
      <label htmlFor={inputId} className="cp-visually-hidden">
        {label}
      </label>
      <input
        ref={ref}
        id={inputId}
        type="search"
        role="searchbox"
        placeholder={label}
        value={value}
        className={[
          "cp-input",
          "cp-search__field",
          showClear && "cp-search__field--clearable",
          `cp-input--${size}`,
          className,
        ]
          .filter(Boolean)
          .join(" ")}
        {...rest}
      />
      {showClear && (
        <button
          type="button"
          className="cp-search__clear"
          aria-label="Limpar pesquisa"
          onClick={onClear}
        >
          ×
        </button>
      )}
    </div>
  );
});

// packages/angular/src/lib/search/search.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";
import type { CpFieldSize } from "../text-input/text-input.component";

let uniqueId = 0;

@Component({
  selector: "cp-search",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="cp-search">
      <span class="cp-search__icon" aria-hidden="true"></span>
      <label [for]="inputId" class="cp-visually-hidden">{{ label }}</label>
      <input
        [id]="inputId"
        type="search"
        role="searchbox"
        [placeholder]="label"
        [value]="value"
        [class]="inputClasses"
        (input)="onInput($event)"
      />
      <button
        *ngIf="showClear"
        type="button"
        class="cp-search__clear"
        aria-label="Limpar pesquisa"
        (click)="onClear()"
      >
        ×
      </button>
    </div>
  `,
})
export class CpSearchComponent {
  @Input() label = "Pesquisar";
  @Input() size: CpFieldSize = "md";
  @Input() value = "";
  @Input() clearable = false;
  @Output() valueChange = new EventEmitter<string>();
  @Output() clear = new EventEmitter<void>();

  readonly inputId = `cp-search-${uniqueId++}`;

  get showClear(): boolean {
    return this.clearable && Boolean(this.value);
  }

  get inputClasses(): string {
    return [
      "cp-input",
      "cp-search__field",
      this.showClear ? "cp-search__field--clearable" : "",
      `cp-input--${this.size}`,
    ]
      .filter(Boolean)
      .join(" ");
  }

  onInput(event: Event): void {
    this.valueChange.emit((event.target as HTMLInputElement).value);
  }

  onClear(): void {
    this.valueChange.emit("");
    this.clear.emit();
  }
}
