// packages/angular/src/lib/tabs/tabs.component.ts
import {
  AfterContentChecked,
  ChangeDetectionStrategy,
  Component,
  ContentChildren,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  QueryList,
  ViewChildren,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { CpTabPanelComponent } from "./tab-panel.component";

export interface CpTabItem {
  id: string;
  label: string;
  disabled?: boolean;
}

let uniqueId = 0;

@Component({
  selector: "cp-tabs",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="cp-tabs">
      <div
        role="tablist"
        [attr.aria-label]="ariaLabel"
        class="cp-tabs__list"
        (keydown)="onKeydown($event)"
      >
        <button
          #tabButton
          *ngFor="let item of items"
          type="button"
          role="tab"
          [id]="idFor(item.id)"
          [attr.aria-selected]="item.id === activeId"
          [attr.aria-controls]="panelIdFor(item.id)"
          [disabled]="item.disabled"
          [attr.tabindex]="item.id === activeId ? 0 : -1"
          [class]="tabClasses(item)"
          (click)="selectTab(item.id)"
        >
          {{ item.label }}
        </button>
      </div>
      <ng-content></ng-content>
    </div>
  `,
})
export class CpTabsComponent implements OnChanges, AfterContentChecked {
  @Input() items: CpTabItem[] = [];
  @Input() activeId = "";
  @Input() ariaLabel = "";
  @Output() activeIdChange = new EventEmitter<string>();

  @ViewChildren("tabButton") tabButtons!: QueryList<ElementRef<HTMLButtonElement>>;
  @ContentChildren(CpTabPanelComponent, { descendants: true })
  panels?: QueryList<CpTabPanelComponent>;

  readonly instanceId = `cp-tabs-${uniqueId++}`;

  ngOnChanges(): void {
    if (!this.activeId) {
      const first = this.items.find((item) => !item.disabled) ?? this.items[0];
      if (first) {
        this.activeId = first.id;
      }
    }
  }

  ngAfterContentChecked(): void {
    this.panels?.forEach((panel) => {
      panel.updateState(panel.id === this.activeId, this.idFor(panel.id), this.panelIdFor(panel.id));
    });
  }

  idFor(id: string): string {
    return `${this.instanceId}-tab-${id}`;
  }

  panelIdFor(id: string): string {
    return `${this.instanceId}-panel-${id}`;
  }

  tabClasses(item: CpTabItem): string {
    return ["cp-tabs__tab", item.id === this.activeId ? "cp-tabs__tab--selected" : ""]
      .filter(Boolean)
      .join(" ");
  }

  selectTab(id: string): void {
    this.activeId = id;
    this.activeIdChange.emit(id);
  }

  onKeydown(event: KeyboardEvent): void {
    const enabled = this.items.filter((item) => !item.disabled);
    const currentIndex = enabled.findIndex((item) => item.id === this.activeId);
    let nextIndex: number | null = null;

    if (event.key === "ArrowRight") nextIndex = (currentIndex + 1) % enabled.length;
    else if (event.key === "ArrowLeft") nextIndex = (currentIndex - 1 + enabled.length) % enabled.length;
    else if (event.key === "Home") nextIndex = 0;
    else if (event.key === "End") nextIndex = enabled.length - 1;

    if (nextIndex !== null) {
      event.preventDefault();
      const next = enabled[nextIndex];
      this.selectTab(next.id);
      const nextIndexInAll = this.items.findIndex((item) => item.id === next.id);
      this.tabButtons.get(nextIndexInAll)?.nativeElement.focus();
    }
  }
}

// packages/react/src/components/Tabs/Tabs.tsx
import { useId, useRef, useState } from "react";
import type { KeyboardEvent, ReactNode } from "react";

export interface TabItem {
  id: string;
  label: ReactNode;
  content: ReactNode;
  disabled?: boolean;
}

export interface TabsProps {
  items: TabItem[];
  defaultValue?: string;
  value?: string;
  onValueChange?: (id: string) => void;
  "aria-label"?: string;
}

export function Tabs({
  items,
  defaultValue,
  value,
  onValueChange,
  "aria-label": ariaLabel,
}: TabsProps) {
  const [internalValue, setInternalValue] = useState(
    defaultValue ?? items.find((item) => !item.disabled)?.id ?? items[0]?.id
  );
  const activeValue = value ?? internalValue;
  const idBase = useId();
  const tabRefs = useRef<Record<string, HTMLButtonElement | null>>({});

  function selectTab(id: string) {
    setInternalValue(id);
    onValueChange?.(id);
  }

  function onKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    const enabled = items.filter((item) => !item.disabled);
    const currentIndex = enabled.findIndex((item) => item.id === activeValue);
    let nextIndex: number | null = null;

    if (event.key === "ArrowRight") nextIndex = (currentIndex + 1) % enabled.length;
    else if (event.key === "ArrowLeft") nextIndex = (currentIndex - 1 + enabled.length) % enabled.length;
    else if (event.key === "Home") nextIndex = 0;
    else if (event.key === "End") nextIndex = enabled.length - 1;

    if (nextIndex !== null) {
      event.preventDefault();
      const next = enabled[nextIndex];
      selectTab(next.id);
      tabRefs.current[next.id]?.focus();
    }
  }

  const activeItem = items.find((item) => item.id === activeValue);

  return (
    <div className="cp-tabs">
      {/* eslint-disable-next-line jsx-a11y/interactive-supports-focus -- por padrão WAI-ARIA APG, o foco vive nos elementos `tab` via roving tabindex, nunca no `tablist` em si. */}
      <div role="tablist" aria-label={ariaLabel} className="cp-tabs__list" onKeyDown={onKeyDown}>
        {items.map((item) => {
          const selected = item.id === activeValue;
          return (
            <button
              key={item.id}
              ref={(el) => {
                tabRefs.current[item.id] = el;
              }}
              type="button"
              role="tab"
              id={`${idBase}-tab-${item.id}`}
              aria-selected={selected}
              aria-controls={`${idBase}-panel-${item.id}`}
              disabled={item.disabled}
              tabIndex={selected ? 0 : -1}
              className={["cp-tabs__tab", selected && "cp-tabs__tab--selected"]
                .filter(Boolean)
                .join(" ")}
              onClick={() => selectTab(item.id)}
            >
              {item.label}
            </button>
          );
        })}
      </div>
      {activeItem && (
        <div
          role="tabpanel"
          id={`${idBase}-panel-${activeItem.id}`}
          aria-labelledby={`${idBase}-tab-${activeItem.id}`}
          className="cp-tabs__panel"
          tabIndex={0}
        >
          {activeItem.content}
        </div>
      )}
    </div>
  );
}
