// packages/react/src/components/TreeView/TreeView.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties, KeyboardEvent } from "react";
import { flattenTree } from "./treeUtils";
import type { TreeNode } from "./treeUtils";

export type { TreeNode };

export interface TreeViewProps {
  label: string;
  nodes: TreeNode[];
  expandedIds: string[];
  onExpandedChange: (ids: string[]) => void;
  selectedId?: string | null;
  onSelect?: (id: string) => void;
}

export function TreeView({
  label,
  nodes,
  expandedIds,
  onExpandedChange,
  selectedId = null,
  onSelect,
}: TreeViewProps) {
  const expandedSet = useMemo(() => new Set(expandedIds), [expandedIds]);
  const flat = useMemo(() => flattenTree(nodes, expandedSet), [nodes, expandedSet]);
  const [activeId, setActiveId] = useState<string | null>(selectedId ?? flat[0]?.node.id ?? null);
  const itemRefs = useRef<Map<string, HTMLLIElement>>(new Map());

  useEffect(() => {
    if (activeId && flat.some((flatNode) => flatNode.node.id === activeId)) return;
    setActiveId(flat[0]?.node.id ?? null);
  }, [flat, activeId]);

  useEffect(() => {
    if (activeId) itemRefs.current.get(activeId)?.focus();
  }, [activeId]);

  const indexById = useMemo(() => {
    const map = new Map<string, number>();
    flat.forEach((flatNode, index) => map.set(flatNode.node.id, index));
    return map;
  }, [flat]);

  function toggleExpand(id: string) {
    const next = new Set(expandedIds);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    onExpandedChange(Array.from(next));
  }

  function selectNode(flatNode: (typeof flat)[number]) {
    if (flatNode.node.disabled) return;
    setActiveId(flatNode.node.id);
    onSelect?.(flatNode.node.id);
  }

  function onKeyDown(event: KeyboardEvent<HTMLLIElement>, flatNode: (typeof flat)[number]) {
    const index = indexById.get(flatNode.node.id) ?? -1;
    const hasChildren = Boolean(flatNode.node.children && flatNode.node.children.length > 0);

    if (event.key === "ArrowDown") {
      event.preventDefault();
      const next = flat[index + 1];
      if (next) setActiveId(next.node.id);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      const prev = flat[index - 1];
      if (prev) setActiveId(prev.node.id);
    } else if (event.key === "ArrowRight") {
      event.preventDefault();
      if (hasChildren && !expandedSet.has(flatNode.node.id)) {
        toggleExpand(flatNode.node.id);
      } else if (hasChildren) {
        const child = flat[index + 1];
        if (child && child.parentId === flatNode.node.id) setActiveId(child.node.id);
      }
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      if (hasChildren && expandedSet.has(flatNode.node.id)) {
        toggleExpand(flatNode.node.id);
      } else if (flatNode.parentId) {
        setActiveId(flatNode.parentId);
      }
    } else if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      selectNode(flatNode);
    }
  }

  return (
    <ul className="cp-tree-view" role="tree" aria-label={label}>
      {flat.map((flatNode) => {
        const { node, depth, posInSet, setSize } = flatNode;
        const hasChildren = Boolean(node.children && node.children.length > 0);
        const expanded = expandedSet.has(node.id);
        const selected = selectedId === node.id;
        const active = activeId === node.id;
        return (
          <li
            key={node.id}
            ref={(el) => {
              if (el) itemRefs.current.set(node.id, el);
              else itemRefs.current.delete(node.id);
            }}
            role="treeitem"
            aria-selected={selected}
            aria-expanded={hasChildren ? expanded : undefined}
            aria-disabled={node.disabled || undefined}
            aria-level={depth + 1}
            aria-posinset={posInSet}
            aria-setsize={setSize}
            tabIndex={active ? 0 : -1}
            className={[
              "cp-tree-view__item",
              selected ? "cp-tree-view__item--selected" : "",
              node.disabled ? "cp-tree-view__item--disabled" : "",
            ]
              .filter(Boolean)
              .join(" ")}
            onKeyDown={(event) => onKeyDown(event, flatNode)}
            onFocus={() => setActiveId(node.id)}
            onClick={() => selectNode(flatNode)}
          >
            <div className="cp-tree-view__row" style={{ "--cp-tree-depth": depth } as CSSProperties}>
              {hasChildren ? (
                <button
                  type="button"
                  className="cp-tree-view__twisty"
                  tabIndex={-1}
                  aria-label={expanded ? "Recolher" : "Expandir"}
                  onClick={(event) => {
                    event.stopPropagation();
                    toggleExpand(node.id);
                  }}
                >
                  {expanded ? "▾" : "▸"}
                </button>
              ) : (
                <span className="cp-tree-view__twisty-spacer" aria-hidden="true" />
              )}
              <span className="cp-tree-view__label">{node.label}</span>
            </div>
          </li>
        );
      })}
    </ul>
  );
}

// packages/angular/src/lib/tree-view/tree-view.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { flattenTree } from "./tree-utils";
import type { FlatTreeNode, TreeNode } from "./tree-utils";

export type { TreeNode };

@Component({
  selector: "cp-tree-view",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ul class="cp-tree-view" role="tree" [attr.aria-label]="label">
      <li
        *ngFor="let flatNode of flat"
        [attr.data-node-id]="flatNode.node.id"
        role="treeitem"
        [attr.aria-selected]="selectedId === flatNode.node.id"
        [attr.aria-expanded]="hasChildren(flatNode) ? expandedSet.has(flatNode.node.id) : null"
        [attr.aria-disabled]="flatNode.node.disabled || null"
        [attr.aria-level]="flatNode.depth + 1"
        [attr.aria-posinset]="flatNode.posInSet"
        [attr.aria-setsize]="flatNode.setSize"
        [tabIndex]="activeId === flatNode.node.id ? 0 : -1"
        [class]="itemClasses(flatNode)"
        (keydown)="onKeydown($event, flatNode)"
        (focus)="activeId = flatNode.node.id"
        (click)="selectNode(flatNode)"
      >
        <div class="cp-tree-view__row" [style.--cp-tree-depth]="flatNode.depth">
          <button
            *ngIf="hasChildren(flatNode)"
            type="button"
            class="cp-tree-view__twisty"
            tabindex="-1"
            [attr.aria-label]="expandedSet.has(flatNode.node.id) ? 'Recolher' : 'Expandir'"
            (click)="onTwistyClick($event, flatNode)"
          >
            {{ expandedSet.has(flatNode.node.id) ? "▾" : "▸" }}
          </button>
          <span *ngIf="!hasChildren(flatNode)" class="cp-tree-view__twisty-spacer" aria-hidden="true"></span>
          <span class="cp-tree-view__label">{{ flatNode.node.label }}</span>
        </div>
      </li>
    </ul>
  `,
})
export class CpTreeViewComponent implements OnChanges {
  @Input() label = "";
  @Input() nodes: TreeNode[] = [];
  @Input() expandedIds: string[] = [];
  @Input() selectedId: string | null = null;
  @Output() expandedChange = new EventEmitter<string[]>();
  @Output() select = new EventEmitter<string>();

  activeId: string | null = null;
  expandedSet = new Set<string>();
  flat: FlatTreeNode[] = [];

  constructor(
    private readonly hostRef: ElementRef<HTMLElement>,
    private readonly cdr: ChangeDetectorRef
  ) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["expandedIds"]) this.expandedSet = new Set(this.expandedIds);
    if (changes["nodes"] || changes["expandedIds"] || changes["selectedId"]) {
      this.flat = flattenTree(this.nodes, this.expandedSet);
      if (!this.activeId || !this.flat.some((flatNode) => flatNode.node.id === this.activeId)) {
        this.activeId = this.selectedId ?? this.flat[0]?.node.id ?? null;
      }
    }
  }

  hasChildren(flatNode: FlatTreeNode): boolean {
    return Boolean(flatNode.node.children && flatNode.node.children.length > 0);
  }

  itemClasses(flatNode: FlatTreeNode): string {
    return [
      "cp-tree-view__item",
      this.selectedId === flatNode.node.id ? "cp-tree-view__item--selected" : "",
      flatNode.node.disabled ? "cp-tree-view__item--disabled" : "",
    ]
      .filter(Boolean)
      .join(" ");
  }

  private toggleExpand(id: string): void {
    const next = new Set(this.expandedIds);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    this.expandedChange.emit(Array.from(next));
  }

  selectNode(flatNode: FlatTreeNode): void {
    if (flatNode.node.disabled) return;
    this.activeId = flatNode.node.id;
    this.select.emit(flatNode.node.id);
  }

  onTwistyClick(event: MouseEvent, flatNode: FlatTreeNode): void {
    event.stopPropagation();
    this.toggleExpand(flatNode.node.id);
  }

  private focusActive(): void {
    this.cdr.detectChanges();
    if (!this.activeId) return;
    this.hostRef.nativeElement
      .querySelector<HTMLLIElement>(`[data-node-id="${this.activeId}"]`)
      ?.focus();
  }

  onKeydown(event: KeyboardEvent, flatNode: FlatTreeNode): void {
    const flat = this.flat;
    const index = flat.findIndex((f) => f.node.id === flatNode.node.id);
    const hasChildren = this.hasChildren(flatNode);

    if (event.key === "ArrowDown") {
      event.preventDefault();
      const next = flat[index + 1];
      if (next) {
        this.activeId = next.node.id;
        this.focusActive();
      }
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      const prev = flat[index - 1];
      if (prev) {
        this.activeId = prev.node.id;
        this.focusActive();
      }
    } else if (event.key === "ArrowRight") {
      event.preventDefault();
      if (hasChildren && !this.expandedSet.has(flatNode.node.id)) {
        this.toggleExpand(flatNode.node.id);
      } else if (hasChildren) {
        const child = flat[index + 1];
        if (child && child.parentId === flatNode.node.id) {
          this.activeId = child.node.id;
          this.focusActive();
        }
      }
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      if (hasChildren && this.expandedSet.has(flatNode.node.id)) {
        this.toggleExpand(flatNode.node.id);
      } else if (flatNode.parentId) {
        this.activeId = flatNode.parentId;
        this.focusActive();
      }
    } else if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      this.selectNode(flatNode);
    }
  }
}
