// packages/angular/src/lib/radio-button/radio-button.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";

let uniqueId = 0;

@Component({
  selector: "cp-radio-button",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [for]="inputId" [class]="wrapperClasses">
      <input
        type="radio"
        [id]="inputId"
        class="cp-radio__input"
        [name]="name"
        [value]="value"
        [disabled]="disabled"
        [checked]="checked"
        (change)="onChange()"
      />
      <span class="cp-radio__circle" aria-hidden="true"></span>
      <span class="cp-radio__label">{{ label }}</span>
    </label>
  `,
})
export class CpRadioButtonComponent {
  @Input() label = "";
  @Input() name = "";
  @Input() value = "";
  @Input() disabled = false;
  @Input() checked = false;
  @Output() valueChange = new EventEmitter<string>();

  readonly inputId = `cp-radio-${uniqueId++}`;

  get wrapperClasses(): string {
    return ["cp-radio", this.disabled ? "cp-radio--disabled" : ""].filter(Boolean).join(" ");
  }

  onChange(): void {
    this.valueChange.emit(this.value);
  }
}

// packages/react/src/components/RadioButton/RadioButton.tsx
import { forwardRef, useId } from "react";
import type { InputHTMLAttributes, ReactNode } from "react";

export interface RadioButtonProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "type"> {
  label: ReactNode;
}

export const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(function RadioButton(
  { label, disabled, className, id, ...rest },
  ref
) {
  const generatedId = useId();
  const inputId = id ?? generatedId;

  return (
    <label
      htmlFor={inputId}
      className={["cp-radio", disabled && "cp-radio--disabled", className]
        .filter(Boolean)
        .join(" ")}
    >
      <input
        ref={ref}
        type="radio"
        id={inputId}
        disabled={disabled}
        className="cp-radio__input"
        {...rest}
      />
      <span className="cp-radio__circle" aria-hidden="true" />
      <span className="cp-radio__label">{label}</span>
    </label>
  );
});
