// packages/angular/src/lib/progress-bar/progress-bar.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

let uniqueId = 0;

@Component({
  selector: "cp-progress-bar",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="cp-progress-bar">
      <div *ngIf="label || showValue" class="cp-progress-bar__header">
        <span *ngIf="label" class="cp-progress-bar__label" [id]="labelId">{{ label }}</span>
        <span *ngIf="showValue && !indeterminate">{{ roundedPercent }}%</span>
      </div>
      <div
        [class]="trackClasses"
        role="progressbar"
        [attr.aria-labelledby]="label ? labelId : null"
        [attr.aria-valuenow]="indeterminate ? null : value"
        [attr.aria-valuemin]="0"
        [attr.aria-valuemax]="max"
      >
        <div class="cp-progress-bar__fill" [style.width.%]="indeterminate ? null : percent"></div>
      </div>
    </div>
  `,
})
export class CpProgressBarComponent {
  @Input() value = 0;
  @Input() max = 100;
  @Input() label = "";
  @Input() showValue = false;
  @Input() indeterminate = false;
  @Input() status: "default" | "danger" = "default";

  readonly labelId = `cp-progress-bar-${uniqueId++}`;

  get percent(): number {
    return Math.min(100, Math.max(0, (this.value / this.max) * 100));
  }

  get roundedPercent(): number {
    return Math.round(this.percent);
  }

  get trackClasses(): string {
    return [
      "cp-progress-bar__track",
      this.status === "danger" ? "cp-progress-bar--danger" : "",
      this.indeterminate ? "cp-progress-bar--indeterminate" : "",
    ]
      .filter(Boolean)
      .join(" ");
  }
}

// packages/react/src/components/ProgressBar/ProgressBar.tsx
import { useId } from "react";
import type { ReactNode } from "react";

export interface ProgressBarProps {
  /** Valor atual entre 0 e max. Omitir junto de indeterminate=true para progresso sem duração previsível. */
  value?: number;
  max?: number;
  label?: ReactNode;
  /** Mostra a percentagem calculada junto ao label. */
  showValue?: boolean;
  indeterminate?: boolean;
  status?: "default" | "danger";
  className?: string;
}

export function ProgressBar({
  value = 0,
  max = 100,
  label,
  showValue = false,
  indeterminate = false,
  status = "default",
  className,
}: ProgressBarProps) {
  const id = useId();
  const percent = Math.min(100, Math.max(0, (value / max) * 100));

  return (
    <div className={["cp-progress-bar", className].filter(Boolean).join(" ")}>
      {(label || showValue) && (
        <div className="cp-progress-bar__header">
          {label && (
            <span className="cp-progress-bar__label" id={id}>
              {label}
            </span>
          )}
          {showValue && !indeterminate && <span>{Math.round(percent)}%</span>}
        </div>
      )}
      <div
        className={[
          "cp-progress-bar__track",
          status === "danger" && "cp-progress-bar--danger",
          indeterminate && "cp-progress-bar--indeterminate",
        ]
          .filter(Boolean)
          .join(" ")}
        role="progressbar"
        aria-labelledby={label ? id : undefined}
        aria-valuenow={indeterminate ? undefined : value}
        aria-valuemin={0}
        aria-valuemax={max}
      >
        <div className="cp-progress-bar__fill" style={indeterminate ? undefined : { width: `${percent}%` }} />
      </div>
    </div>
  );
}
