// packages/react/src/components/FileUploader/FileUploader.tsx
import { useState } from "react";
import type { ChangeEvent, DragEvent, ReactNode } from "react";

export interface FileUploaderProps {
  label?: ReactNode;
  files: File[];
  onChange: (files: File[]) => void;
  accept?: string;
  multiple?: boolean;
  maxSizeBytes?: number;
  helperText?: ReactNode;
  errorText?: ReactNode;
  disabled?: boolean;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function FileUploader({
  label,
  files,
  onChange,
  accept,
  multiple = false,
  maxSizeBytes,
  helperText,
  errorText,
  disabled = false,
}: FileUploaderProps) {
  const [dragging, setDragging] = useState(false);
  const invalid = Boolean(errorText);

  function addFiles(list: FileList | null) {
    if (!list || list.length === 0) return;
    const incoming = Array.from(list);
    onChange(multiple ? [...files, ...incoming] : incoming.slice(0, 1));
  }

  function onInputChange(event: ChangeEvent<HTMLInputElement>) {
    addFiles(event.target.files);
    event.target.value = "";
  }

  function onDragOver(event: DragEvent<HTMLLabelElement>) {
    event.preventDefault();
    if (!disabled) setDragging(true);
  }

  function onDrop(event: DragEvent<HTMLLabelElement>) {
    event.preventDefault();
    setDragging(false);
    if (disabled) return;
    addFiles(event.dataTransfer.files);
  }

  function removeAt(index: number) {
    onChange(files.filter((_, i) => i !== index));
  }

  return (
    <div className="cp-field">
      {label && <span className="cp-field__label">{label}</span>}
      <div className="cp-file-uploader">
        <label
          className={[
            "cp-file-uploader__dropzone",
            dragging ? "cp-file-uploader__dropzone--dragging" : "",
            invalid ? "cp-file-uploader__dropzone--invalid" : "",
            disabled ? "cp-file-uploader__dropzone--disabled" : "",
          ]
            .filter(Boolean)
            .join(" ")}
          onDragOver={onDragOver}
          onDragLeave={() => setDragging(false)}
          onDrop={onDrop}
        >
          <input
            type="file"
            className="cp-visually-hidden"
            accept={accept}
            multiple={multiple}
            disabled={disabled}
            onChange={onInputChange}
          />
          <span className="cp-file-uploader__icon" aria-hidden="true">
            ↑
          </span>
          <span className="cp-file-uploader__hint">Arraste ficheiros para aqui ou clique para procurar</span>
        </label>
        {files.length > 0 && (
          <ul className="cp-file-uploader__list">
            {files.map((file, index) => {
              const oversize = Boolean(maxSizeBytes) && file.size > (maxSizeBytes as number);
              return (
                <li
                  key={`${file.name}-${index}`}
                  className={`cp-file-uploader__item${oversize ? " cp-file-uploader__item--invalid" : ""}`}
                >
                  <span className="cp-file-uploader__item-name">{file.name}</span>
                  <span className="cp-file-uploader__item-size">
                    {oversize ? "Excede o tamanho máximo" : formatBytes(file.size)}
                  </span>
                  <button
                    type="button"
                    className="cp-file-uploader__item-remove"
                    aria-label={`Remover ${file.name}`}
                    onClick={() => removeAt(index)}
                  >
                    ×
                  </button>
                </li>
              );
            })}
          </ul>
        )}
      </div>
      {(errorText || helperText) && (
        <span className={`cp-field__helper${errorText ? " cp-field__helper--error" : ""}`}>
          {errorText || helperText}
        </span>
      )}
    </div>
  );
}

// packages/angular/src/lib/file-uploader/file-uploader.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "cp-file-uploader",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="cp-field">
      <span *ngIf="label" class="cp-field__label">{{ label }}</span>
      <div class="cp-file-uploader">
        <label
          [class]="dropzoneClasses"
          (dragover)="onDragOver($event)"
          (dragleave)="dragging = false"
          (drop)="onDrop($event)"
        >
          <input
            type="file"
            class="cp-visually-hidden"
            [attr.accept]="accept || null"
            [multiple]="multiple"
            [disabled]="disabled"
            (change)="onInputChange($event)"
          />
          <span class="cp-file-uploader__icon" aria-hidden="true">↑</span>
          <span class="cp-file-uploader__hint">Arraste ficheiros para aqui ou clique para procurar</span>
        </label>
        <ul *ngIf="value.length > 0" class="cp-file-uploader__list">
          <li *ngFor="let file of value; let i = index" [class]="itemClasses(file)">
            <span class="cp-file-uploader__item-name">{{ file.name }}</span>
            <span class="cp-file-uploader__item-size">
              {{ isOversize(file) ? "Excede o tamanho máximo" : formatBytes(file.size) }}
            </span>
            <button
              type="button"
              class="cp-file-uploader__item-remove"
              [attr.aria-label]="'Remover ' + file.name"
              (click)="removeAt(i)"
            >
              ×
            </button>
          </li>
        </ul>
      </div>
      <span *ngIf="errorText || helperText" [class]="helperClasses">{{ errorText || helperText }}</span>
    </div>
  `,
})
export class CpFileUploaderComponent {
  @Input() label = "";
  @Input() value: File[] = [];
  @Input() accept = "";
  @Input() multiple = false;
  @Input() maxSizeBytes: number | null = null;
  @Input() helperText = "";
  @Input() errorText = "";
  @Input() disabled = false;
  @Output() valueChange = new EventEmitter<File[]>();

  dragging = false;

  get dropzoneClasses(): string {
    return [
      "cp-file-uploader__dropzone",
      this.dragging ? "cp-file-uploader__dropzone--dragging" : "",
      this.errorText ? "cp-file-uploader__dropzone--invalid" : "",
      this.disabled ? "cp-file-uploader__dropzone--disabled" : "",
    ]
      .filter(Boolean)
      .join(" ");
  }

  get helperClasses(): string {
    return ["cp-field__helper", this.errorText ? "cp-field__helper--error" : ""]
      .filter(Boolean)
      .join(" ");
  }

  itemClasses(file: File): string {
    return ["cp-file-uploader__item", this.isOversize(file) ? "cp-file-uploader__item--invalid" : ""]
      .filter(Boolean)
      .join(" ");
  }

  isOversize(file: File): boolean {
    return Boolean(this.maxSizeBytes) && file.size > (this.maxSizeBytes as number);
  }

  formatBytes(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  private addFiles(list: FileList | null): void {
    if (!list || list.length === 0) return;
    const incoming = Array.from(list);
    this.valueChange.emit(this.multiple ? [...this.value, ...incoming] : incoming.slice(0, 1));
  }

  onInputChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.addFiles(target.files);
    target.value = "";
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
    if (!this.disabled) this.dragging = true;
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.dragging = false;
    if (this.disabled) return;
    this.addFiles(event.dataTransfer?.files ?? null);
  }

  removeAt(index: number): void {
    this.valueChange.emit(this.value.filter((_, i) => i !== index));
  }
}
